apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auditor
            image: gsasig/chronos:0.01
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster ; env
          restartPolicy: OnFailure
